const API_BASE_URL_DEVELOPMENT = 'http://localhost:5055';
const API_BASE_URL_PRODUCTION = '';

const ENDPOINTS ={
    GET_TODO: 'todo_get',
    CREATE_TODO: 'todo_insert',
    UPDATE_TODO: 'todo_update',
    DELETE_TODO_BY_ID: 'todo_del',

    GET_EVENT_DAY: 'eventday',
    GET_EVENT_MONTH: 'eventmonth',
    CREATE_EVENT: 'event_insert',
    UPDATE_EVENT: 'event_update',
    DELETE_EVENT_BY_ID: 'event_delete'
};


const development = {
API_URL_GET_TODO : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_TODO}`,
API_URL_CREATE_TODO : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_TODO}`,
API_URL_UPDATE_TODO : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_TODO}`,
API_URL_DELETE_TODO_BY_ID : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_TODO_BY_ID}`,

API_URL_GET_EVENTS_FOR_MONTH : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_EVENT_MONTH}`,
API_URL_GET_EVENTS_FOR_DAY : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_EVENT_DAY}`,
API_URL_CREATE_EVENT : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_EVENT}`,
API_URL_UPDATE_EVENT : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_EVENT}`,
API_URL_DELETE_EVENT_BY_ID : `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_EVENT_BY_ID}`,
};

const production = {
    API_URL_GET_TODO : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_TODO}`,
    API_URL_CREATE_TODO : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_TODO}`,
    API_URL_UPDATE_TODO : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_TODO}`,
    API_URL_DELETE_TODO_BY_ID : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_TODO_BY_ID}`,

    API_URL_GET_EVENTS_FOR_MONTH : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_EVENT_MONTH}`,
API_URL_GET_EVENTS_FOR_DAY : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_EVENT_DAY}`,
API_URL_CREATE_EVENT : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_EVENT}`,
API_URL_UPDATE_EVENT : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_EVENT}`,
API_URL_DELETE_EVENT_BY_ID : `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_EVENT_BY_ID}`,
};


    const Constants = process.env.NODE_ENV === 'development' ? development : production;

    export default Constants;